import datetime
import os

USE_GOVCLOUD = os.environ.get("USE_GOVCLOUD") == "on"
USE_NAT_GATEWAY = os.environ.get("USE_NAT_GATEWAY") == "on"

# Must be last to tag all resources
# Always import EKS modules (same for standard and GovCloud)
from . import assets  # noqa: F401, E402
from . import cache  # noqa: F401, E402
from . import database  # noqa: F401, E402
from . import eks  # noqa: F401, E402
from . import logs  # noqa: F401, E402
from . import repository  # noqa: F401, E402
from . import tags  # noqa: F401, E402
from . import template  # noqa: F401, E402
from . import vpc  # noqa: F401, E402

# Since we're outputting YAML, we can include comments
print("# This Cloudformation stack template was generated by")
print("# https://github.com/caktus/aws-web-stacks")
print("# at %s" % datetime.datetime.now())
print("# with parameters:")
parms_used = sorted(parm for parm in os.environ.keys() if parm.startswith("USE_") or parm == "DEFAULTS_FILE")
for parm in parms_used:
    print("#\t%s = %s" % (parm, os.environ[parm]))
print()
print(template.template.to_yaml(), end='')
